version: '3.8'

services:
  # Main application for development
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-http://localhost:54321}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    command: npm run dev -- --host 0.0.0.0
    networks:
      - dev-network

  # Production build testing
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    networks:
      - dev-network

  # Testing environment
  app-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - CI=true
    command: npm run test:run
    networks:
      - dev-network

  # E2E Testing with Playwright
  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - CI=true
    command: npx playwright test
    depends_on:
      - app-dev
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge