
-- Let's create workflow templates with the correct type values that match the constraint
-- First, let's see what types are allowed by using only known valid values
INSERT INTO workflow_templates (id, name, type, description, created_by, is_active) VALUES
('880e8400-e29b-41d4-a716-446655440000', 'White Glove Listing Launch', 'Listing', 'Premium listing workflow for luxury properties with comprehensive marketing and staging', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1), true),
('880e8400-e29b-41d4-a716-446655440001', 'Elite Buyer Representation', 'Buyer', 'High-end buyer representation workflow with personalized service', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1), true),
('880e8400-e29b-41d4-a716-446655440002', 'Core Transaction Management', 'Listing', 'Standard transaction coordination for core service tier', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1), true),
('880e8400-e29b-41d4-a716-446655440003', 'Closing Coordination - All Tiers', 'General', 'Comprehensive closing coordination workflow', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1), true),
('880e8400-e29b-41d4-a716-446655440004', 'First-Time Buyer Support', 'Buyer', 'Enhanced support workflow for first-time buyers', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1), true);

-- Create comprehensive email templates
INSERT INTO email_templates (id, name, subject, body_html, category, created_by) VALUES
('990e8400-e29b-41d4-a716-446655440000', 'White Glove Welcome', 'Welcome to Our White Glove Service', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;"><h2 style="color: #2c3e50;">Welcome to The Agent Concierge Co.</h2><p>Dear {{client_name}},</p><p>Thank you for choosing our White Glove service for your luxury real estate transaction at <strong>{{property_address}}</strong>. You can expect the highest level of personalized attention and expertise throughout this process.</p><div style="background: #f8f9fa; padding: 15px; border-left: 4px solid #007bff; margin: 20px 0;"><h4>What to Expect:</h4><ul><li>Dedicated transaction coordinator</li><li>Weekly progress updates</li><li>Premium marketing materials</li><li>Concierge-level service</li></ul></div><p>Your dedicated coordinator will be in touch within 24 hours to discuss your timeline and preferences.</p><p>Best regards,<br><strong>{{agent_name}}</strong><br>{{agent_company}}</p></div>', 'welcome', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1)),

('990e8400-e29b-41d4-a716-446655440001', 'Weekly Transaction Update', 'Weekly Update: {{property_address}}', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;"><h3 style="color: #2c3e50;">Transaction Update - Week of {{current_date}}</h3><p>Dear {{client_name}},</p><p>Here is your weekly update on the transaction for <strong>{{property_address}}</strong>:</p><div style="background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 15px 0;"><h4>Current Status</h4><ul><li><strong>Status:</strong> {{transaction_status}}</li><li><strong>Closing Date:</strong> {{closing_date}}</li><li><strong>Purchase Price:</strong> ${{purchase_price}}</li></ul></div><div style="background: #e8f5e8; padding: 15px; border-radius: 5px; margin: 15px 0;"><h4>Recent Activity</h4><p>{{recent_activity}}</p></div><div style="background: #fff3cd; padding: 15px; border-radius: 5px; margin: 15px 0;"><h4>Upcoming This Week</h4><p>{{upcoming_tasks}}</p></div><p>Please don''t hesitate to reach out with any questions or concerns.</p><p>Best regards,<br><strong>{{agent_name}}</strong></p></div>', 'updates', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1)),

('990e8400-e29b-41d4-a716-446655440002', 'New Listing Announcement', 'New Luxury Listing: {{property_address}}', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;"><h2 style="color: #2c3e50;">Exclusive New Listing</h2><p>We are pleased to present this exceptional property:</p><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; margin: 20px 0;"><h3 style="margin: 0; color: white;">{{property_address}}</h3><p style="font-size: 18px; margin: 10px 0;"><strong>Price: ${{purchase_price}}</strong></p><p>{{property_description}}</p></div><div style="background: #f8f9fa; padding: 15px; border-radius: 5px;"><h4>Property Highlights:</h4><ul><li>Prime location in {{city}}</li><li>Luxury finishes throughout</li><li>Professional photography completed</li><li>Comprehensive marketing campaign</li></ul></div><p style="text-align: center; margin: 30px 0;"><a href="{{listing_url}}" style="background: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; display: inline-block;">View Full Listing</a></p><p>For private showings or more information, please contact:</p><p><strong>{{agent_name}}</strong><br>{{agent_phone}}<br>{{agent_email}}</p></div>', 'marketing', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1)),

('990e8400-e29b-41d4-a716-446655440003', 'Contract Acceptance Notification', 'Contract Accepted - {{property_address}}', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="background: #d4edda; border: 1px solid #c3e6cb; padding: 20px; border-radius: 10px; margin-bottom: 20px;"><h3 style="color: #155724; margin: 0;">🎉 Congratulations!</h3></div><p>Dear {{client_name}},</p><p><strong>Great news!</strong> Your offer on {{property_address}} has been accepted.</p><div style="background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0;"><h4>Transaction Details:</h4><ul><li><strong>Purchase Price:</strong> ${{purchase_price}}</li><li><strong>Closing Date:</strong> {{closing_date}}</li><li><strong>Property:</strong> {{property_address}}</li></ul></div><div style="background: #fff3cd; padding: 15px; border-radius: 5px; margin: 20px 0;"><h4>Next Steps:</h4><ol><li>Home inspection scheduled for {{inspection_date}}</li><li>Financing coordination begins immediately</li><li>Title work initiation</li><li>Appraisal scheduling</li><li>Insurance coordination</li></ol></div><p>We will keep you updated throughout the process and ensure everything moves smoothly toward closing.</p><p><strong>Congratulations again on this exciting milestone!</strong></p><p>Best regards,<br><strong>{{agent_name}}</strong><br>{{agent_company}}</p></div>', 'notifications', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1)),

('990e8400-e29b-41d4-a716-446655440004', 'First-Time Buyer Guide', 'Your Home Buying Journey Begins', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;"><h2 style="color: #2c3e50;">🏠 Welcome to Homeownership!</h2><p>Dear {{client_name}},</p><p>Congratulations on taking the first step toward homeownership! As your dedicated agent, I am here to guide you through every step of this exciting process.</p><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; margin: 20px 0;"><h4 style="color: white; margin-top: 0;">Your Home Buying Journey:</h4><ul style="list-style: none; padding: 0;"><li style="margin: 10px 0;">✅ Pre-approval assistance</li><li style="margin: 10px 0;">🏡 Property search and showings</li><li style="margin: 10px 0;">📝 Offer preparation and negotiation</li><li style="margin: 10px 0;">🔍 Home inspection coordination</li><li style="margin: 10px 0;">💰 Financing support</li><li style="margin: 10px 0;">📋 Closing preparation</li></ul></div><div style="background: #e8f5e8; padding: 15px; border-radius: 5px; margin: 20px 0;"><h4>Why Choose Our First-Time Buyer Program:</h4><ul><li>Patient, educational approach</li><li>Access to first-time buyer programs</li><li>FHA and VA loan expertise</li><li>Down payment assistance guidance</li><li>Closing cost optimization</li></ul></div><p>I will be available to answer all your questions and ensure you feel confident throughout your home buying journey. No question is too small!</p><p>Let''s schedule your buyer consultation to get started.</p><p>Best regards,<br><strong>{{agent_name}}</strong><br>First-Time Buyer Specialist<br>{{agent_phone}}</p></div>', 'welcome', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1)),

('990e8400-e29b-41d4-a716-446655440005', 'Inspection Reminder', 'Home Inspection Scheduled - {{property_address}}', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;"><h3 style="color: #2c3e50;">🔍 Home Inspection Scheduled</h3><p>Dear {{client_name}},</p><p>Your home inspection has been scheduled for:</p><div style="background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0;"><h4>Inspection Details:</h4><ul><li><strong>Property:</strong> {{property_address}}</li><li><strong>Date:</strong> {{inspection_date}}</li><li><strong>Time:</strong> {{inspection_time}}</li><li><strong>Inspector:</strong> {{inspector_name}}</li><li><strong>Phone:</strong> {{inspector_phone}}</li></ul></div><div style="background: #fff3cd; padding: 15px; border-radius: 5px; margin: 20px 0;"><h4>What to Expect:</h4><ul><li>Inspection typically takes 2-4 hours</li><li>You''re encouraged to attend</li><li>Ask questions during the inspection</li><li>Report will be available within 24 hours</li></ul></div><p>This inspection is a crucial step in your home buying process. Please plan to attend if possible.</p><p>Best regards,<br><strong>{{agent_name}}</strong></p></div>', 'notifications', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1)),

('990e8400-e29b-41d4-a716-446655440006', 'Closing Reminder', 'Closing Scheduled - Final Details', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;"><div style="background: #d1ecf1; border: 1px solid #bee5eb; padding: 20px; border-radius: 10px; margin-bottom: 20px;"><h3 style="color: #0c5460; margin: 0;">🎉 Almost There - Closing Details</h3></div><p>Dear {{client_name}},</p><p>We''re excited to inform you that your closing has been scheduled!</p><div style="background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0;"><h4>Closing Information:</h4><ul><li><strong>Date:</strong> {{closing_date}}</li><li><strong>Time:</strong> {{closing_time}}</li><li><strong>Location:</strong> {{closing_location}}</li><li><strong>Title Company:</strong> {{title_company}}</li></ul></div><div style="background: #fff3cd; padding: 15px; border-radius: 5px; margin: 20px 0;"><h4>What to Bring:</h4><ul><li>Government-issued photo ID</li><li>Certified funds for closing costs</li><li>Homeowner''s insurance policy</li><li>Any required documentation</li></ul></div><div style="background: #f8d7da; padding: 15px; border-radius: 5px; margin: 20px 0;"><h4>Important Reminders:</h4><ul><li>Final walk-through scheduled for {{walkthrough_date}}</li><li>Ensure utilities are scheduled for transfer</li><li>Plan for key pickup after closing</li></ul></div><p>Congratulations on reaching this milestone! We''ll see you at closing.</p><p>Best regards,<br><strong>{{agent_name}}</strong></p></div>', 'notifications', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1)),

('990e8400-e29b-41d4-a716-446655440007', 'Price Reduction Notice', 'Price Adjustment - {{property_address}}', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;"><h3 style="color: #2c3e50;">📈 Strategic Price Adjustment</h3><p>Dear {{client_name}},</p><p>Based on current market conditions and buyer feedback, we recommend a strategic price adjustment for your property:</p><div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; margin: 20px 0;"><h4 style="color: white; margin-top: 0;">{{property_address}}</h4><p style="font-size: 18px;"><strong>New Price: ${{new_price}}</strong></p><p style="font-size: 14px;">Previous Price: ${{old_price}}</p></div><div style="background: #e8f5e8; padding: 15px; border-radius: 5px; margin: 20px 0;"><h4>Market Analysis:</h4><ul><li>{{market_analysis_point_1}}</li><li>{{market_analysis_point_2}}</li><li>{{market_analysis_point_3}}</li></ul></div><p>This adjustment positions your property competitively in the current market and should generate renewed buyer interest.</p><p>Best regards,<br><strong>{{agent_name}}</strong></p></div>', 'marketing', (SELECT id FROM profiles WHERE role = 'coordinator' LIMIT 1));

-- Create template tasks for the workflow templates
INSERT INTO template_tasks (id, template_id, subject, description_notes, due_date_rule, phase, is_agent_visible, sort_order) VALUES
-- White Glove Listing Launch tasks
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440000', 'Initial Client Consultation', 'Conduct comprehensive listing consultation with sellers. Review pricing strategy, marketing plan, and timeline expectations.', '{"type": "days_from_event", "days": 0, "event": "ratified_date"}', 'Pre-Listing', true, 1),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440000', 'Professional Photography Scheduling', 'Schedule luxury property photography session. Coordinate with photographer for optimal lighting and staging preparation.', '{"type": "days_from_event", "days": 3, "event": "ratified_date"}', 'Pre-Listing', true, 2),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440000', 'Home Staging Consultation', 'Arrange staging consultation with professional stager. Review furniture placement and décor recommendations.', '{"type": "days_from_event", "days": 5, "event": "ratified_date"}', 'Pre-Listing', true, 3),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440000', 'Market Analysis & CMA', 'Complete comprehensive market analysis and comparative market analysis for luxury property pricing.', '{"type": "days_from_event", "days": 2, "event": "ratified_date"}', 'Pre-Listing', false, 4),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440000', 'Luxury Marketing Materials Creation', 'Create premium marketing materials including brochures, virtual tour, and social media content.', '{"type": "days_from_event", "days": 7, "event": "ratified_date"}', 'Marketing', false, 5),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440000', 'MLS Listing Launch', 'Launch property on MLS with professional photos and detailed description.', '{"type": "days_from_event", "days": 10, "event": "ratified_date"}', 'Marketing', true, 6),

-- Elite Buyer Representation tasks  
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440001', 'Buyer Consultation & Needs Analysis', 'Comprehensive buyer consultation to understand needs, timeline, and financial capabilities.', '{"type": "days_from_event", "days": 0, "event": "ratified_date"}', 'Initial Consultation', true, 1),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440001', 'Pre-Approval Coordination', 'Coordinate with preferred lenders for mortgage pre-approval process.', '{"type": "days_from_event", "days": 1, "event": "ratified_date"}', 'Financing', true, 2),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440001', 'Customized Property Search Setup', 'Set up customized property search criteria and automated notifications.', '{"type": "days_from_event", "days": 2, "event": "ratified_date"}', 'Property Search', false, 3),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440001', 'Schedule Property Showings', 'Coordinate and schedule property showings based on buyer preferences.', '{"type": "days_from_event", "days": 7, "event": "ratified_date"}', 'Property Search', true, 4),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440001', 'Offer Strategy Discussion', 'Discuss offer strategy, terms, and negotiation approach with buyers.', '{"type": "days_from_event", "days": 14, "event": "ratified_date"}', 'Offer Preparation', true, 5),

-- Core Transaction Management tasks
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440002', 'Transaction File Setup', 'Create transaction file and input all relevant client and property information.', '{"type": "days_from_event", "days": 0, "event": "ratified_date"}', 'Setup', false, 1),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440002', 'Send Welcome Email', 'Send welcome email to client explaining transaction process and timeline.', '{"type": "days_from_event", "days": 1, "event": "ratified_date"}', 'Communication', false, 2),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440002', 'Review Purchase Contract', 'Review purchase contract for completeness and accuracy of all terms.', '{"type": "days_from_event", "days": 1, "event": "ratified_date"}', 'Contract Review', false, 3),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440002', 'Schedule Home Inspection', 'Coordinate and schedule home inspection with qualified inspector.', '{"type": "days_from_event", "days": 3, "event": "ratified_date"}', 'Inspections', true, 4),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440002', 'Order Appraisal', 'Order property appraisal through buyer''s lender or approved appraiser.', '{"type": "days_from_event", "days": 5, "event": "ratified_date"}', 'Appraisal', false, 5),

-- Closing Coordination tasks
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440003', 'Title Company Coordination', 'Contact title company to initiate title search and coordinate closing.', '{"type": "days_from_event", "days": -30, "event": "closing_date"}', 'Title Work', false, 1),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440003', 'Loan Processing Follow-up', 'Follow up with lender on loan processing status and required documentation.', '{"type": "days_from_event", "days": -21, "event": "closing_date"}', 'Financing', false, 2),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440003', 'Schedule Final Walk-Through', 'Schedule final walk-through inspection prior to closing.', '{"type": "days_from_event", "days": -3, "event": "closing_date"}', 'Final Steps', true, 3),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440003', 'Closing Document Review', 'Review all closing documents for accuracy before closing appointment.', '{"type": "days_from_event", "days": -2, "event": "closing_date"}', 'Final Steps', false, 4),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440003', 'Coordinate Key Transfer', 'Coordinate key transfer and property possession with all parties.', '{"type": "days_from_event", "days": 0, "event": "closing_date"}', 'Closing Day', true, 5),

-- First-Time Buyer Support tasks
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440004', 'First-Time Buyer Education', 'Provide comprehensive first-time buyer education and process overview.', '{"type": "days_from_event", "days": 0, "event": "ratified_date"}', 'Education', true, 1),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440004', 'Down Payment Assistance Research', 'Research available down payment assistance programs and grants.', '{"type": "days_from_event", "days": 1, "event": "ratified_date"}', 'Financial Planning', false, 2),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440004', 'FHA/VA Loan Consultation', 'Consult on FHA, VA, and other first-time buyer loan programs.', '{"type": "days_from_event", "days": 2, "event": "ratified_date"}', 'Financial Planning', true, 3),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440004', 'Homeowner Insurance Education', 'Educate buyer on homeowner insurance requirements and options.', '{"type": "days_from_event", "days": 7, "event": "ratified_date"}', 'Education', true, 4),
(gen_random_uuid(), '880e8400-e29b-41d4-a716-446655440004', 'Closing Cost Breakdown', 'Provide detailed breakdown of closing costs and cash required.', '{"type": "days_from_event", "days": 10, "event": "ratified_date"}', 'Financial Planning', true, 5);
