// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdupublcyigkgdlobzqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkdXB1YmxjeWlna2dkbG9ienFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjI1OTcsImV4cCI6MjA2NTQ5ODU5N30.8xcZdS2x53VNpVR6Dn2YVu6Di0J2fmugvdzj46UJxi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);